# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_is_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_updated',
            field=models.CharField(choices=[(0, b'false'), (1, b'true')], default=0, max_length=1),
        ),
    ]
