# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('int_pdp_map_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_sku', models.CharField(blank=True, default=b'', max_length=100)),
                ('domestic_pdp_url', models.TextField(blank=True, default=b'')),
                ('domestic_pid', models.CharField(blank=True, default=b'', max_length=100)),
                ('international_pdp_url', models.TextField(blank=True, default=b'')),
                ('international_pid', models.CharField(blank=True, default=b'', max_length=100)),
                ('is_active', models.CharField(choices=[(0, b'false'), (1, b'true')], default=1, max_length=1)),
            ],
            options={
                'ordering': ('created',),
                'db_table': 'international_pdp_mapping',
            },
        ),
    ]
