# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_updated',
            field=models.CharField(choices=[(0, b'false'), (1, b'true')], default=1, max_length=1),
        ),
    ]
